before_install:
  - gem update bundle
  - gem --version
  - bundle --version
language: ruby
rvm:
  - "2.0.0-p247"
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-20mode # JRuby in 2.0 mode
  - rbx-19mode
  - rbx-20mode
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec 
